### PR TITLE
Freelinks: support `~` for local link suppression

### PR DESCRIPTION
**Pull request by s793016**
## Summary

Implements the first part of [#9964](https://github.com/TiddlyWiki/TiddlyWiki5/issues/9964): allow a recognised Freelink match to be locally suppressed by prefixing it with `~`.

```text
~Title → Title as plain text
```

The escaped title is not rendered as a Freelink, and the `~` escape character is not shown in the rendered output.

This covers non-CamelCase Freelink titles for which the `~` prefix remains available to the Freelinks text widget, including titles containing spaces, numbers, or non-Latin characters.

Examples:

```text
~Homer                 → Homer, plain text
~1984                  → 1984, plain text
~The Lord of the Rings → The Lord of the Rings, plain text
~中文標題                → 中文標題, plain text
```

When Freelinks is disabled, this behaviour is inactive and the source text remains unchanged.

## Implementation

The change is limited to the Freelinks text-widget override.

- During title-match selection, a recognised match immediately preceded by `~` is treated as escaped and is not added to the rendered Freelink matches.
- The escape character is recorded only when it successfully suppresses a recognised Freelink match.
- When plain-text parse-tree nodes are generated, recorded escape characters are omitted from rendered output.
- The render-path condition now also adopts a transformed single plain-text node. This is required for inputs such as `~Homer`, where the output changes from one plain-text node to another but does not contain a link node.

The implementation does not remove unrelated `~` characters:

```text
~UnknownTitle → ~UnknownTitle
~~Homer       → ~Homer
```

For `~~Homer`, the second `~` escapes the recognised `Homer` match, while the first `~` remains literal text.

## CamelCase limitation

Native CamelCase parser rules may consume the `~` prefix before the Freelinks text widget runs. Supporting escaped CamelCase titles therefore requires a follow-up core/parser-level mechanism that preserves the escape state for Freelinks to consume.

## Testing

Verified manually with Freelinks enabled:

```text
Existing title: Homer
Input:          ~Homer
Expected:       Homer as plain text, without a Freelink or visible `~`

Existing title: 1984
Input:          ~1984
Expected:       1984 as plain text, without a Freelink or visible `~`

Existing title: 中文標題
Input:          ~中文標題
Expected:       中文標題 as plain text, without a Freelink or visible `~`

Unknown title:
Input:          ~UnknownTitle
Expected:       ~UnknownTitle remains unchanged

Freelinks disabled:
Input:          ~Homer
Expected:       ~Homer remains unchanged
```

### CODE REVIEW

**Comment by pmario** [comment]
The parseTreeNode already contains some info about prefixed text elements. If there is no prefix `role=undefined`... But I am not sure if that's good enough

```
if(this.parseTreeNode.rule === "wikilinkprefix") { /* leave alone */ }
```

**Comment by pmario** [comment]
Eg: `~Odysseus` is rendered as plain text, and the tilde will be removed once the tiddler exists. 

As I wrote: The core has to provide the basics first.

image

**Comment by s793016** [comment]
I think there are two separate topics here.

The first is the explicit local escape proposed in #9964:

```text
~Title
```

For Freelink titles that do not match the native CamelCase `wikiLink` pattern, the `~` prefix remains available to the Freelinks text widget. This PR implements that case:

```text
~Homer                 → Homer as plain text
~1984                  → 1984 as plain text
~The Lord of the Rings → The Lord of the Rings as plain text
~中文標題                → 中文標題 as plain text
```

The `~` is removed only if it directly prefixes a recognised Freelink match. Otherwise it remains ordinary text:

```text
~UnknownTitle → ~UnknownTitle
```

Before implementing this, I tested the relevant native parser behaviour:

| Input | Matches the native `wikiLink` pattern | Is `~` consumed before Freelinks runs? |
| --- | --- | --- |
| `~CamelCaseTitle` | Yes | Yes |
| `~TwoCaps` | Yes | Yes |
| `~Title` | No | No |
| `~title` | No | No |
| `~1984` | No | No |
| `~The Lord of the Rings` | No | No |
| `~中文標題` | No | No |

The central remaining question is what should happen to an explicit `~CamelCase` prefix when normal CamelCase linking is disabled.

The native `wikilink` rule may be disabled, so bare CamelCase text is no longer automatically linked. However, the separate `wikilinkprefix` rule can still recognise `~CamelCaseTitle` and remove the prefix before Freelinks runs.

The core first needs to decide whether that is the intended behaviour. If native CamelCase linking is disabled, should:

```text
~CamelCaseTitle → ~CamelCaseTitle
```

remain literal text, or should the prefix continue to express an automatic-link escape?

Only if the latter is intended does a second question arise. `wikilink.js` / `wikilinkprefix.js` currently turn `~CamelCaseTitle` into an ordinary plain-text node before Freelinks runs. Freelinks cannot distinguish it from an unescaped `CamelCaseTitle` and may linkify it again.

In that case, the parser needs a way to preserve the semantic information that the text was explicitly escaped from automatic linking. The exact representation—parse-tree metadata, a dedicated node type, or another parser-level mechanism—should be decided by the core.

The proposed “link only one occurrence per title per tiddler” behaviour is potentially useful for reducing over-linkification, but I think it is a separate policy feature. It needs independent rules for which occurrence is retained, interaction with longest-match selection, `IgnoreCase`, `MaxLinks`, transclusions, and explicit `~` escapes. It does not solve the loss of the explicit `~` state for CamelCase-shaped text.

Therefore, this PR intentionally covers the part Freelinks can implement independently. The semantics of `~CamelCase` when normal CamelCase linking is disabled, and any required parser support for preserving that semantic state, should be discussed separately.

**Comment by pmario** [comment]
I did run some tests and came to the same conclusion. I also want to have some new configurations that I did mention in the other posts. More experiments are needed.

**Comment by pmario** [comment]
While experimenting I found a bug and a fix.

2 tiddler **titles**

- cost$100
- cost

test tiddler **text**: `cost$100` -> `TypeError: node.$.push is not a function`

I do have a fix. I'll create a PR soon, with some more changes to the freelinks plugin. ... 

---

The current implementation has some duplicated core code, which can cause source drift between the core and the plugin. 

As I wrote, the core can call 2 hooks, that can help freelinks quite a bit. It also is more performant to build the index, after an edit.

**Comment by s793016** [comment]
> While experimenting I found a bug and a fix.
> 2 tiddler **titles**
>     * cost$100
>     * cost
> test tiddler **text**: `cost$100` -> `TypeError: node.$.push is not a function`
> I do have a fix. I'll create a PR soon, with some more changes to the freelinks plugin. ...
> The current implementation has some duplicated core code, which can cause source drift between the core and the plugin.
> As I wrote, the core can call 2 hooks, that can help freelinks quite a bit. It also is more performant to build the index, after an edit.

Thanks — I think #9971 is now the better place for the longer-term implementation.

I found this while importing a real title corpus for testing, rather than from a synthetic unit case.

I used a Python import script to build a wiki from approximately 10,000 English dictionary entries, 10,000 idiom/slang entries, and the Bible. With that corpus loaded, Freelinks in #9969 stopped working entirely.

The immediate cause is that there are 68 non-system tiddler titles containing `$`. The `$:/` exclusion does not filter these titles, because they do not start with `$:/`; examples include `$100 hamburger` and `SystemTag: $:/tags/...`.

The Aho-Corasick trie currently uses `$` as its internal output property while also using title characters as trie-edge keys. A legitimate `$` in a title can therefore collide with that internal property and produce errors such as:

    child.$.concat is not a function

A minimal reproduction is a corpus containing both `cost` and `cost$100`.

This appears to be a separate matcher/indexer issue, rather than part of the `~Title` escape prototype, so I am not adding that change to #9969. Renaming the internal output property to a non-character field such as `__freelinkOutputs` would avoid this collision. Using null-prototype trie nodes may also be worth considering for arbitrary title keys.

I will leave #9969 as the minimal escape prototype and use this corpus as a regression test for the direction taken in #9971.
